### ISSUE TITLE
Specifying Both nerves_system_br and TARGET-Specific Patches in BR2_GLOBAL_PATCH_DIR

### ISSUE THREAD

**Issue by masahiro-999** [masahiro-999/core_mp135#2]
I am referring to the configuration from this repository:
https://github.com/m5stack/CoreMP135_buildroot-external-st.git
It is necessary to apply patches to the optee-os and arm-trusted-firmware packages.

In nerves_defconfig, the nerves_system_br directory is specified, and it is not possible to designate patches specific to the TARGET.
```BR2_GLOBAL_PATCH_DIR="${BR2_EXTERNAL_NERVES_PATH}/patches```

I resolved the issue by creating a patches directory, placing the TARGET-specific patches there, and copying the patches from nerves_system_br into this directory:
```BR2_GLOBAL_PATCH_DIR="${NERVES_DEFCONFIG_DIR}/patches```

If there is a proper way to specify both the nerves_system_br and the TARGET-specific patches, I would like to update the configuration accordingly.

**In Japanese**
https://github.com/m5stack/CoreMP135_buildroot-external-st.git
この設定を参考にしている。
optee-os, arm-trusted-firmwareパッケージにパッチをあてる必要がある。

nerves_defconfigでは、nerves_system_brのディレクトリが指定されていて、TARGET独自のパッチを指定する事ができない。
BR2_GLOBAL_PATCH_DIR="${BR2_EXTERNAL_NERVES_PATH}/patches"

patchesディレクトリを作成して、TARGET独自のPatchを置き、ここに、nerves_system_brにあるパッチをコピーすることで、解決をしている。
BR2_GLOBAL_PATCH_DIR="${NERVES_DEFCONFIG_DIR}/patches"

nerves_system_brとTARGET独自のパッチを両方指定する適切な方法があれば修正したい

**Comment by pojiro** [comment]
カーネルのパッチであれば、 `nerves_system_bbb` 等はターゲット固有のパッチを以下の行で当てているので参考になると思います。

https://github.com/nerves-project/nerves_system_bbb/blob/v2.24.0/nerves_defconfig#L33

linux ディレクトリ配下にターゲット固有のパッチがあります。

https://github.com/nerves-project/nerves_system_bbb/tree/v2.24.0/linux

**Comment by masahiro-999** [comment]
コメントありがとうございます。カーネルパッチだったらこの方法でできそうですね。
optee-os, arm-trusted-firmwareパッケージには個別のPatch指定がみあたらず行き詰りました。

**Comment by pojiro** [comment]
あー、カーネルではなく、buildroot のパッケージにターゲット固有のパッチを当てたいってことでしたか（？まだわかってない）

`BR2_GLOBAL_PATCH_DIR` は 複数ディレクトリ指定できるようですが、それではだめですか？

> The BR2_GLOBAL_PATCH_DIR configuration option can be used to specify a space separated list of one or more directories containing package patches.

ref. https://buildroot.org/downloads/manual/manual.html#_adding_project_specific_patches_and_hashes

**Comment by masahiro-999** [comment]
これです！
スペース区切りでで、複数ディレクトリ指定できました。解決できそうです。ありがとうございました。
